require('config.remap')
require('config.options')
require('config.filetypes').setup()
require('plugins.plugins')
require('config.lsp')
require('config.treesitter').setup()
require('config.autocmd')
require('config.mappings')
